IMAGE_SUBMITTED = "image.submitted"
INFERENCE_COMPLETED = "inference.completed"
ANNOTATION_STORED = "annotation.stored"
EMBEDDING_CREATED = "embedding.created"
QUERY_SUBMITTED = "query.submitted"
QUERY_COMPLETED = "query.completed"
IMAGE_QUERY_SUBMITTED = "image.query_submitted"
IMAGE_QUERY_COMPLETED = "image.query_completed"
ANNOTATION_CORRECTED = "annotation.corrected"
SYSTEM_ERROR = "system.error"

ALL_TOPICS = {
    IMAGE_SUBMITTED,
    INFERENCE_COMPLETED,
    ANNOTATION_STORED,
    EMBEDDING_CREATED,
    QUERY_SUBMITTED,
    QUERY_COMPLETED,
    IMAGE_QUERY_SUBMITTED,
    IMAGE_QUERY_COMPLETED,
    ANNOTATION_CORRECTED,
    SYSTEM_ERROR,
}
